name: 'User CI to Docker Hub and K8s Repo'

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPO: 'uniunity/user-service'
  K8S_REPO: 'https://github.com/Uniunity-msa/k8s.git'
  SERVICE_NAME: 'user-service'

jobs:
  build-and-update:
    name: 'Build Docker Image and Update K8s'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Image Tag (Datetime)
      run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Create mail_token.js and mail_credentials.json from Secrets
      run: |
        touch ./src/config/mail_token.json
        touch ./src/config/mail_credentials.json
        # mail_token.json 작성
        cat <<EOF > ./src/config/mail_token.json
        ${{ secrets.MAIL_TOKEN }}
        EOF
        echo "mail_token.json 파일 생성 완료"
    
        # mail_credentials.json 작성
        cat <<EOF > ./src/config/mail_credentials.json
        {
          "web":{
            "client_id":"742965004576-draoep626ua7nv4he4kj1e73u9112nph.apps.googleusercontent.com",
            "project_id":"uniunity-455912",
            "auth_uri":"https://accounts.google.com/o/oauth2/auth",
            "token_uri":"https://oauth2.googleapis.com/token",
            "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
            "client_secret": "${{ secrets.CLIENT_SECRET }}",
            "redirect_uris":["http://localhost:3000/oauth2callback"]
            }
        }
        EOF
        echo "mail_credentials.json 파일 생성 완료"  

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Install Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/

    - name: Clone K8s Repo
      run: |
        git clone https://x-access-token:${{ secrets.K8S_REPO_TOKEN }}@github.com/Uniunity-msa/k8s.git
        cd k8s
        git config user.email "ci@github.com"
        git config user.name "GitHub Actions"

    - name: Update kustomization.yaml Image Tag
      run: |
        cd k8s/${{ env.SERVICE_NAME }}
        kustomize edit set image ${{ env.DOCKERHUB_REPO }}=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}

    - name: Commit and Push Changes to K8s Repo
      run: |
        cd k8s
        git add .
        git commit -m "build : Update ${{ env.SERVICE_NAME }} image tag to ${{ env.IMAGE_TAG }}"
        git push origin main
