name: 'User CI to Docker Hub and K8s Repo'

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPO: 'uniunity/user-service'
  K8S_REPO: 'https://github.com/Uniunity-msa/k8s.git'
  SERVICE_NAME: 'user-service'

jobs:
  build-and-update:
    name: 'Build Docker Image and Update K8s'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Image Tag (Datetime)
      run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Create mail_token.js and mail_credentials.json from Secrets
      run: |
        mkdir -p ./src/config
        cat <<EOF > ./src/config/mail_token.js
module.exports = "${{ secrets.MAIL_TOKEN }}";
EOF
        echo "mail_token.js 파일 생성 완료"

        cat <<EOF > ./src/config/mail_credentials.json
${{ secrets.MAIL_CREDENTIALS }}
EOF
        echo "mail_credentials.json 파일 생성 완료"

    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    - name: Clone K8s Repo
      run: |
        git clone https://x-access-token:${{ secrets.K8S_REPO_TOKEN }}@github.com/Uniunity-msa/k8s.git
        cd k8s
        git config user.email "ci@github.com"
        git config user.name "GitHub Actions"

    - name: Update kustomization.yaml Image Tag
      run: |
        cd k8s/apps/${{ env.SERVICE_NAME }}
        sed -i "s|name: ${{ env.DOCKERHUB_REPO }}.*|name: ${{ env.DOCKERHUB_REPO }}\n    newTag: ${{ env.IMAGE_TAG }}|" kustomization.yaml

    - name: Commit and Push Changes to K8s Repo
      run: |
        cd k8s
        git add .
        git commit -m "Update ${{ env.SERVICE_NAME }} image tag to ${{ env.IMAGE_TAG }}"
        git push origin main
