name: 'User CI to Docker Hub'

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_REPO: 'uniunity/user-service'

jobs:
  docker:
    name: 'Build and Push to Docker Hub'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Image Tag (Datetime)
      run: echo "IMAGE_TAG=$(TZ=Asia/Seoul date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Create mail_token.js and mail_credentials.json from Secrets
      run: |
        touch ./src/config/mail_token.js
        touch ./src/config/mail_credentials.json
        # mail_token.js 작성
        cat <<EOF > ./src/config/mail_token.js
        ${{ secrets.MAIL_TOKEN }}
        EOF
        echo "mail_token.js 파일 생성 완료"
    
        # mail_credentials.json 작성
        cat <<EOF > ./src/config/mail_credentials.json
        ${{ secrets.MAIL_CREDENTIALS }}
        EOF
        echo "mail_credentials.json 파일 생성 완료"  



    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_URI=${{ env.DOCKERHUB_REPO }}:${{ env.IMAGE_TAG }}
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
